// seeds: 79 14 55 13

// seed-to-soil map:
// 50 98 2
// 52 50 48

input = { seeds ~ map+ }

seeds = { "seeds:" ~ number+ }

map = { map_title ~ "map:" ~ range_mapping+ }

map_title = { #source = name ~ "-to-" ~ #dest = name }

range_mapping = { #dest_start = number ~ #source_start = number ~ #length = number }

name = @{ ASCII_ALPHA+ }

number = @{ ASCII_DIGIT+ }

WHITESPACE = _{ " " | "\t" | "\n" }
